### ISSUE TITLE
Can not click navigation 

### ISSUE THREAD

**Issue by aziziqbal** [gaetansenn/vue3-carousel-nuxt#1]
Hi, i have problem with nvaigation. When data slide more than 1 i can't click navigation and always disable. I already check in html element and the slide more than 1 but navigation detect just 1 data

**Comment by gaetansenn** [comment]
Hi @aziziqbal,
This repository is only the compatible module for NuxtJS you should open the issue on the official repository that this module is using. https://github.com/ismail9k/vue3-carousel

**Comment by aziziqbal** [comment]
hi @gaetansenn  i use nuxt 3 for this issue

**Comment by gaetansenn** [comment]
I know but this module just injecting the components and css of the official repository automatically.Check the code you will more understand. Don't hesitate to add a star 😊
