### ISSUE TITLE
Cannot read properties of undefined (reading 'defineComponent')

### ISSUE THREAD

**Issue by MuhammadKhizar7** [gaetansenn/vue3-carousel-nuxt#12]
Installing it to nuxt app result in this error "Cannot read properties of undefined (reading 'defineComponent')"
just copy basic example this
```
<template>
  <Carousel>
    <Slide v-for="slide in 10" :key="slide">
      <div class="carousel__item">{{ slide }}</div>
    </Slide>

    <template #addons>
      <Navigation />
      <Pagination />
    </template>
  </Carousel>
</template>

<script>
import { defineComponent } from 'vue'
import { Carousel, Navigation, Pagination, Slide } from 'vue3-carousel'

import 'vue3-carousel/dist/carousel.css'

export default defineComponent({
  name: 'Basic',
  components: {
    Carousel,
    Slide,
    Pagination,
    Navigation,
  },
})
</script>

<style>
.carousel__item {
  min-height: 200px;
  width: 100%;
  background-color: var(--vc-clr-primary);
  color: var(--vc-clr-white);
  font-size: 20px;
  border-radius: 8px;
  display: flex;
  justify-content: center;
  align-items: center;
}

.carousel__slide {
  padding: 10px;
}

.carousel__prev,
.carousel__next {
  box-sizing: content-box;
  border: 5px solid white;
}
</style>


```

**Comment by gaetansenn** [comment]
Hello,

You should remove the import of the components it's automatic. Please check the documentation or playground folder. 

Thank you

**Comment by Iran-110** [comment]
Hi, this is because the latest release of `vue3-carousel@0.3.3` that adds `"type": "module"` to `package.json`.
(this commit: https://github.com/ismail9k/vue3-carousel/commit/603d7a99cd71bc3f3b7a4cd12c226a009dade745)

After this release, nuxt's resolver confuses the esm file and loads `vue3-carousel/dist/carousel.js` instead of `vue3-carousel/dist/carousel.es.js`.

The connection of this package to `vue3-carousel` is here:
https://github.com/gaetansenn/vue3-carousel-nuxt/blob/381bef8cc9e1012286755b1ce4d89f0bf68d745b/src/module.ts#L19

For now, to solve this problem, what I did was to add the following line in the nuxt settings:
```ts
export default defineNuxtConfig({
  // ...
  alias: {
    'vue3-carousel/dist/carousel': 'vue3-carousel/dist/carousel.es.js',
  },
});
```

**Comment by MuhammadKhizar7** [comment]
Doing this fixed the issue https://github.com/gaetansenn/vue3-carousel-nuxt/issues/12#issuecomment-2037042315 thanks @Iran-110

**Comment by gaetansenn** [comment]
Thank you for your feedback @Iran-110 just release a new version that add the alias from the module. @MuhammadKhizar7 you can upgrade the package and remove the alias now ;) 

https://github.com/gaetansenn/vue3-carousel-nuxt/releases/tag/v1.1.1

**Comment by luckys** [comment]
I have the same issue but in my case I upgraded nuxt from v3.10.1 to v3.11.2 and vue3-carousel-nuxt to v1.1.1
The error that I get is this:
```
Cannot read properties of undefined (reading 'defineComponent')

at ./node_modules/vue3-carousel/dist/carousel.js:9:78
at ./node_modules/vue3-carousel/dist/carousel.js:10:3
at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
at async ViteNodeRunner.interopedImport (./node_modules/vite-node/dist/client.mjs:383:28)
at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:253:24)
at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:189:14)
at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:233:12)
at async ./components/talkual-ui/TKCarousel/TKCarousel.js:4:31
```

This is my custom component:

```
<template>
  <Carousel
    :class="carouselClass"
    :wrap-around="wrapItems"
    :items-to-show="visibleItems"
    :autoplay="autoplay"
    :items-to-scroll="numScroll"
  >
    <Slide
      v-for="(item, index) in data"
      :key="index"
    >
      <div
        :class="slideClass"
      >
        <NuxtImg
          v-if="item.image"
          :src="item.image"
          :alt="item.name"
          :class="imageClass"
          loading="lazy"
          format="webp"
        />
        <div :class="slotClass">
          <slot
            name="SlideContent"
            :item="item"
            :class="slotClass"
          />
        </div>
      </div>
    </Slide>

    <template #addons>
      <Navigation v-if="showNavigation">
        <template #prev>
          <span class="mdi mdi-chevron-left bg-green-tertiary rounded-full  text-green-primary leading-none inline-flex justify-center items-center text-[24px]" />
        </template>
        <template #next>
          <span class="mdi mdi-chevron-right bg-green-tertiary rounded-full  text-green-primary leading-none inline-flex justify-center items-center text-[24px]" />
        </template>
      </Navigation>
      <Pagination v-if="showPagination" :class="paginationClass"/>
    </template>
  </Carousel>
</template>

<script setup lang="ts">
import type { PropType } from 'vue';
import { Carousel, Navigation, Pagination, Slide } from 'vue3-carousel';
import type { CarouselSlideObject } from './TKCarouselTypes';

defineProps({
  data: {
    type: Array as PropType<CarouselSlideObject[]>,
    required: true
  },
    visibleItems: {
        type: Number,
        default: 1
    },
    showNavigation: {
        type: Boolean,
        default: true
    },
    showPagination: {
        type: Boolean,
        default: true
    },
    autoplay: {
        type: Number,
        default: 0
    },
    wrapItems: {
        type: Boolean,
        default: true
    },
    slideClass: {
        type: String,
        default: ''
    },
    carouselClass: {
        type: String,
        default: ''
    },
    imageClass: {
        type: String,
        default: ''
    },
    slotClass: {
        type: String,
        default: ''
    },
    paginationClass: {
        type: String,
        default: ''
    },
    numScroll: {
        type: Number,
        default: 1
    }
})
</script>

<style lang="scss" scoped>

.carousel__pagination {
  height: 0px;

  :deep button {
    position: relative;
    bottom: 25px;
    background-color: white;
    margin-left: 6px;
    border-radius: 100%;
    height: 11px;
    width: 11px;
  }

  :deep button::after {
    display: none!important;
  }
}
:deep .carousel__pagination-button.carousel__pagination-button--active {
  background-color: hsl(68 83% 63%)
}
</style>
```
In the previous version of nuxt it was working well.

**Comment by gaetansenn** [comment]
Hello @luckys can you try without importing the import { Carousel, Navigation, Pagination, Slide } from 'vue3-carousel'; as nuxt already import them that the purpose of the module. 
Normally it's working with the last version of nuxt. You can check it from the playground folder of this repository.

**Comment by luckys** [comment]
@gaetansenn Thanks for you quick reply. That's fixed my issue!!

**Comment by gaetansenn** [comment]
Don't hesitate to star the repository ;)

**Comment by mursalin3sit** [comment]
I have faced the same problem with the vue3-carousel-nuxt latest version. The error I got was:

` ERROR  Cannot read properties of undefined (reading 'defineComponent')

  at /C:/Users/USER/Desktop/Vuejs-project/vinix/vinix-vue-loan-funding-company-template/vinix-nuxt/vinix-nuxt-static/vinix/node_modules/vue3-carousel/dist/carousel.js:280:27
  at /C:/Users/USER/Desktop/Vuejs-project/vinix/vinix-vue-loan-funding-company-template/vinix-nuxt/vinix-nuxt-static/vinix/node_modules/vue3-carousel/dist/carousel.js:9:78
  at /C:/Users/USER/Desktop/Vuejs-project/vinix/vinix-vue-loan-funding-company-template/vinix-nuxt/vinix-nuxt-static/vinix/node_modules/vue3-carousel/dist/carousel.js:10:3
  at ModuleJob.run (node:internal/modules/esm/module_job:194:25)`

This is my component

`<template>
  <div class="partner-area ptb-100">
    <div class="container">
      <div class="partner-slider">
        <carousel
          :autoplay="8000"
          :settings="settings"
          :wrap-around="true"
          :breakpoints="breakpoints"
        >
          <slide v-for="slide in carouselItems" :key="slide.id">
            <div class="partner-item">
              <img :src="slide.image" alt="image" />
            </div>
          </slide>
        </carousel>
      </div>
    </div>
  </div>
</template>
  
<script>
import { defineComponent } from "vue";
import { Carousel, Slide } from "vue3-carousel";

import "vue3-carousel/dist/carousel.css";

import image1 from "../../assets/img/partner/1.png";
import image2 from "../../assets/img/partner/2.png";
import image3 from "../../assets/img/partner/3.png";
import image4 from "../../assets/img/partner/4.png";
import image5 from "../../assets/img/partner/5.png";

export default defineComponent({
  name: "Partner",
  components: {
    Carousel,
    Slide,
  },
  data: () => ({
    settings: {
      itemsToShow: 1,
      snapAlign: "center",
    },
    carouselItems: [
      {
        id: 1,
        image: image1,
      },
      {
        id: 2,
        image: image2,
      },
      {
        id: 3,
        image: image3,
      },
      {
        id: 4,
        image: image4,
      },
      {
        id: 5,
        image: image5,
      },
      {
        id: 6,
        image: image1,
      },
      {
        id: 7,
        image: image2,
      },
      {
        id: 8,
        image: image3,
      },
    ],
    breakpoints: {
      0: {
        itemsToShow: 1,
        snapAlign: "center",
      },
      576: {
        itemsToShow: 1,
        snapAlign: "center",
      },
      768: {
        itemsToShow: 3,
        snapAlign: "center",
      },
      992: {
        itemsToShow: 4,
        snapAlign: "left",
      },
      1200: {
        itemsToShow: 5,
        snapAlign: "center",
      },
    },
  }),
});
</script>`

**Comment by mursalin3sit** [comment]
I have faced the same problem with the vue3-carousel-nuxt latest versition. The error I got was: [Screenshot](https://prnt.sc/gfXrbzZjP_Wa)

This is my code: [Screenshot](https://prnt.sc/TdCVUCBaby2W)

**Comment by mursalin3sit** [comment]
I have faced the same problem with the vue3-carousel-nuxt latest versition. The error I got was: [Screenshot](https://prnt.sc/gfXrbzZjP_Wa)

This is my code: [Screenshot](https://prnt.sc/UHP8DB0_oodm)

**Comment by gaetansenn** [comment]
@mursalin3sit please read the last comment on this issue this will fix your issue.

**Comment by mursalin3sit** [comment]
@gaetansenn I'm trying without importing. [Screenshot](https://prnt.sc/EEAGE2RgWg3F)

But the carousel is not working. [Screenshot](https://prnt.sc/3X2Ic-_l4t8l)

**Comment by gaetansenn** [comment]
Dont import the css it's already imported now it's more about configuration of the carousel. I leave you with the official documentation

**Comment by mursalin3sit** [comment]
@gaetansenn My problem is fixed. Thanks for your quick reply.

**Comment by Sajjad3223** [comment]
> Hi, this is because the latest release of `vue3-carousel@0.3.3` that adds `"type": "module"` to `package.json`. (this commit: [ismail9k/vue3-carousel@603d7a9](https://github.com/ismail9k/vue3-carousel/commit/603d7a99cd71bc3f3b7a4cd12c226a009dade745))
> 
> After this release, nuxt's resolver confuses the esm file and loads `vue3-carousel/dist/carousel.js` instead of `vue3-carousel/dist/carousel.es.js`.
> 
> The connection of this package to `vue3-carousel` is here:
> 
> https://github.com/gaetansenn/vue3-carousel-nuxt/blob/381bef8cc9e1012286755b1ce4d89f0bf68d745b/src/module.ts#L19
> 
> For now, to solve this problem, what I did was to add the following line in the nuxt settings:
> 
> ```ts
> export default defineNuxtConfig({
>   // ...
>   alias: {
>     'vue3-carousel/dist/carousel': 'vue3-carousel/dist/carousel.es.js',
>   },
> });
> ```
Thank you very much, this solution worked for me, I was struggling a lot thank you.

**Comment by gaetansenn** [comment]
Hello @Sajjad3223 you dont need to add the alias the last version now add it automatically: https://github.com/gaetansenn/vue3-carousel-nuxt/releases/tag/v1.1.1

**Comment by Sajjad3223** [comment]
Hi @gaetansenn , I installed it today and it's the latest version but it was giving me the defineComponent Error, I have the version v1.1.1 installed, after adding alias the problem solved

**Comment by gsennua** [comment]
@Sajjad3223 Do you have a reproduction link with the 1.1.1 and the defineComponent error ?

**Comment by Sajjad3223** [comment]
@gsennua Unfortunately No, But I can send information I tried to use,
in nuxt.config.ts:
```
export default defineNuxtConfig({
  modules: ["@pinia/nuxt", "vue3-carousel-nuxt"],
  alias: {
    // This is for fixing " Cannot read properties of undefined (reading 'defineComponent') " error
    'vue3-carousel/dist/carousel': 'vue3-carousel/dist/carousel.es.js',
  },
  carousel:{
    prefix:'GP'
  },
})
```
in package.json:
```
...
"devDependencies": {
    "autoprefixer": "^10.4.17",
    "nuxt": "^3.10.3",
    "postcss": "^8.4.33",
    "tailwindcss": "^3.4.1",
    "vue": "^3.4.14",
    "vue-router": "^4.2.5",
    "vue3-carousel-nuxt": "^1.1.1"
  },
...
```
and it's how I used Carousel in vue pages:
```
<GPCarousel :items-to-show="1" class="rounded-xl overflow-hidden">
      <GPSlide v-for="i in 4" :key="i">
        <NuxtLink to="/market" class="w-full shrink-0 relative">
          <img src="~/assets/images/banner.png" alt="banner" class="w-full">
          <span class="absolute right-4 top-4 bg-gray-200 rounded-full w-6 h-6 grid place-items-center pt-0.5">{{ i }}</span>
        </NuxtLink>
      </GPSlide>
    </GPCarousel>
```

**Comment by mursalin3sit** [comment]
@Sajjad3223 Can you check [nuxt.config.ts](https://github.com/gaetansenn/vue3-carousel-nuxt/blob/master/playground/nuxt.config.ts) and [app.vue](https://github.com/gaetansenn/vue3-carousel-nuxt/blob/381bef8cc9e1012286755b1ce4d89f0bf68d745b/playground/app.vue) inside this `vue3-carousel-nuxt/playground`.
