### ISSUE TITLE
Missing "./dist/carousel.es.js" specifier in "vue3-carousel"

### ISSUE THREAD

**Issue by milailijevic** [gaetansenn/vue3-carousel-nuxt#15]
Happening with the [0.3.4](https://github.com/ismail9k/vue3-carousel/commit/62015e12ec6d1695e0335b8d429b05ec68e53f2f) vue3-carousel version update. Can you check please?

**Comment by gaetansenn** [comment]
Hi @milailijevic can you give me a reproduction link ? The playground is still working with the 0.3.4 version.

**Comment by milailijevic** [comment]
Sure [here you go](https://stackblitz.com/edit/vue3-carousel-nuxt)
The error appeared along with the vue3-carousel update.

**Comment by gaetansenn** [comment]
Hi @milailijevic should be resolved now. The 0.3.4 now fix the esm resolution from this commit https://github.com/ismail9k/vue3-carousel/commit/1661f0e1d3c61be651a026fa9edfbfcffcdfdfcf
