### ISSUE TITLE
Question about ssr

### ISSUE THREAD

**Issue by w3bsite** [gaetansenn/vue3-carousel-nuxt#3]
Hi thanks for the awesome work , I wanted to ask if the component runs on the server or if it waits for DOM to load like swiper js

**Comment by gaetansenn** [comment]
Hi,
As explained in the readme this module is just loading the official module.
From my knowledge the library can be run on the server but the calculation of the slider is done during the mounted lifecycle so on the client side.
Please refer to the official repository for more information.

Regards,

Gaetan
