### ISSUE TITLE
when I use vue3-carousel-nuxt i got error

### ISSUE THREAD

**Issue by m-sam-mohamadi** [gaetansenn/vue3-carousel-nuxt#6]
Hi 
I have some issues with vue3-carousel-nuxt and I dont't know how to solve it

when I use vue3-carousel-nuxt as a module i got this error:
Cannot read properties of undefined (reading 'value')

I saw errors source and errors was from this code:
![screenshot](https://github.com/gaetansenn/vue3-carousel-nuxt/assets/64077684/b254194a-537f-40e4-87c8-6e0beebf2e66)

my carousel config:

`<Carousel
        dir="rtl"
        ref="carousel"
        :items-to-show="2"
        :items-to-scroll="1"
        :autoplay="5000"
        :wrapAround="true"
        :snap-align="'center'"
        :breakpoints="breakPoints"
        :pause-autoplay-on-hover="true"
        class="mb-6" 
      ></Carousel>`

**Comment by m-sam-mohamadi** [comment]
it's like carousel has problem with pagination

I removed the pagination code and the errors gone :]

**Comment by gaetansenn** [comment]
hi @m-sam-mohamadi this module is just injecting the official vue3-carousel please open an issue on the official repository if you think there is a problem with the library.

**Comment by m-sam-mohamadi** [comment]
thanks @gaetansenn
but i use vue3-carousel as a plugin its worked

thanks anyway
